# Generated by Django 5.2 on 2025-04-21 16:32

import app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_alter_bb_content_alter_bb_price_alter_bb_title'), ('app', '0003_alter_bb_title')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('spares', models.ManyToManyField(to='app.spare')),
            ],
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^.{4,}$')], verbose_name='Заголовок')),
                ('price', models.FloatField(blank=True, null=True, validators=[app.models.MinMaxValueValidator(max_value=1000, min_value=0), app.models.validate_even], verbose_name='Цена')),
                ('content', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rubric')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published'],
            },
        ),
    ]
