# Generated by Django 5.2 on 2025-04-21 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial_squashed_0003_alter_bb_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Контент'),
        ),
    ]

