# Generated by Django 5.2 on 2025-04-23 14:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bb_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[app.models.MinMaxValueValidator(max_value=1000, min_value=0)], verbose_name='Цена'),
        ),
    ]
