# Generated by Django 5.2 on 2025-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
